### ISSUE TITLE
Crash when opening dimension nbt

### ISSUE THREAD

**Issue by inxomnyaa** [protolambda/blocktopograph#1]
Hello! Awesome project, figured out on Reddit that this is open source.
I use it to develop MCPE server software, http://github.com/clearskyteam/pocketmine-mp, thanks to your app i was able to fix en/deconding issues and finally add really long missing entities/blocks. (pistons)

I experienced a crash when i open 'dimension1' or 'dimension2' nbt. My character currently was in the overworld, so 'dimension0'.

(Also, sidenote: do you know where the filled_map (item) nbt is saved? how do you figure out where what key is?)

**Comment by jocopa3** [comment]
I can quickly answer your sidenote: 

Find the filled_map uuid from the extra tag data:
![](http://i.imgur.com/LJCsu33.png)

Open a custom tag and enter in: **map\__uuid_**
![](http://i.imgur.com/ctcwjyu.png)

The NBT structure should look like this:
![](http://i.imgur.com/NtgxyBa.png)

**Comment by inxomnyaa** [comment]
Awsome man, Thanks alot!
I actually tried the map_*uuid*, seems like i mistyped it. Whats that leveldb viewer you got there?
And thanks alot, i acually had the keys by inspecting mcpe with IDA Pro 
![image](https://cloud.githubusercontent.com/assets/8733998/22421105/e79dfd22-e6e5-11e6-9a8b-abd345e68474.png)

**Comment by inxomnyaa** [comment]
@jocopa3 i figured out what viewer this is, and downloaded it. But how do you open the custom tag? (seems like you have an updated version)

**Comment by inxomnyaa** [comment]
New note: the dimension1+dimension2 nbt were empty. I emptied another value too, seems like all empty nbt's crash the app.

**Comment by protolambda** [comment]
Closing this issue, I guess it is resolved, but feel free to re-open if necessary.
