### ISSUE TITLE
Crash when reading NBT

### ISSUE THREAD

**Issue by Creeperface01** [protolambda/blocktopograph#3]
App crashes if I try to open for example Item NBT (for example firework data).

**Comment by Creeperface01** [comment]
its a list of Compound tags and if I open one of Compound tags it crashes

**Comment by Creeperface01** [comment]
in the compound tag should be 2 byte arrays and 3 byte tags

**Comment by protolambda** [comment]
I stopped working on this app long ago, and it has been delisted from the app-store for quite a while now.
