### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by ghost** [protolambda/blocktopograph#4]
Minecraft Bedrock edition 1.2.7 released, but the map is not visible in the blocktopograph.
Not working Multi-player NBT and advenced nbt options.

This app is latest support leveldb NBT Editor.

**Comment by protolambda** [comment]
I stopped working on this app long ago, and it has been delisted from the app-store for quite a while now.

If you want an update, you could ask @MithrilMania, who updated the level-db dependency, and was planning to make some additions. Everyone is free to copy the project, and update it themselves.

**Comment by inxomnyaa** [comment]
Oh. Thats actually sad.
